name: MineMaze
version: 2.1
main: me.Laubi.MineMaze.MineMazePlugin
author: Laubi

depend: [WorldEdit]


commands:
    /maze:
        useage: "/maze [args]"
        description: "'Core'-Command for all subcommands"